profiles:
  default:
    owner: shashank
    timezone: Asia/Kolkata
    os: windows
    shells:
      - pwsh
    repos:
      cams_memory_public: "~\\Desktop\\cams-hub\\cams-memory-public"
    notes:
      - "No secrets stored here. Keys/tokens are local-only via environment."